import type { Metadata } from "next";
import "../globals.css";
import ClerkProviders from "./providers/ClerkProviders";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ClerkProviders>{children}</ClerkProviders>
      </body>
    </html>
  );
}
